services:
  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgres/18/docker
    restart: unless-stopped
    networks:
      - tablero_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - TABLERO_SERVER_HOSTNAME=${TABLERO_SERVER_HOSTNAME}
      - TABLERO_SERVER_PORT=${TABLERO_SERVER_PORT}
      - TABLERO_JWKS_URL=http://frontend:${FRONTEND_PORT}/api/auth/jwks
    networks:
      - tablero_network
    ports:
      - "${TABLERO_SERVER_PORT}:${TABLERO_SERVER_PORT}"
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - BETTER_AUTH_URL=${BETTER_AUTH_URL}
        - ORIGIN=${ORIGIN}
        - UPLOAD_DIR=${UPLOAD_DIR}
        - BACKEND_URL=http://backend:${TABLERO_SERVER_PORT}
    depends_on:
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - ORIGIN=${ORIGIN}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - BACKEND_URL=http://backend:${TABLERO_SERVER_PORT}
    networks:
      - tablero_network
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - avatars:/app/uploads

networks:
  tablero_network:

volumes:
  pgdata:
  avatars: